const WORD_CATALOG = [
  { english: 'dog', chinese: '狗', emoji: '🐶', category: 'animals' },
  { english: 'cat', chinese: '猫', emoji: '🐱', category: 'animals' },
  { english: 'rabbit', chinese: '兔子', emoji: '🐰', category: 'animals' },
  { english: 'bird', chinese: '鸟', emoji: '🐦', category: 'animals' },
  { english: 'fish', chinese: '鱼', emoji: '🐟', category: 'animals' },
  { english: 'elephant', chinese: '大象', emoji: '🐘', category: 'animals' },
  { english: 'monkey', chinese: '猴子', emoji: '🐵', category: 'animals' },
  { english: 'bear', chinese: '熊', emoji: '🐻', category: 'animals' },
  { english: 'panda', chinese: '熊猫', emoji: '🐼', category: 'animals' },
  { english: 'lion', chinese: '狮子', emoji: '🦁', category: 'animals' },
  { english: 'tiger', chinese: '老虎', emoji: '🐯', category: 'animals' },
  { english: 'horse', chinese: '马', emoji: '🐴', category: 'animals' },
  { english: 'pig', chinese: '猪', emoji: '🐷', category: 'animals' },
  { english: 'cow', chinese: '牛', emoji: '🐮', category: 'animals' },
  { english: 'sheep', chinese: '羊', emoji: '🐑', category: 'animals' },
  { english: 'duck', chinese: '鸭子', emoji: '🦆', category: 'animals' },
  { english: 'chicken', chinese: '鸡', emoji: '🐔', category: 'animals' },
  { english: 'frog', chinese: '青蛙', emoji: '🐸', category: 'animals' },
  { english: 'snake', chinese: '蛇', emoji: '🐍', category: 'animals' },
  { english: 'butterfly', chinese: '蝴蝶', emoji: '🦋', category: 'animals' },

  { english: 'apple', chinese: '苹果', emoji: '🍎', category: 'fruits' },
  { english: 'banana', chinese: '香蕉', emoji: '🍌', category: 'fruits' },
  { english: 'orange', chinese: '橙子', emoji: '🍊', category: 'fruits' },
  { english: 'grape', chinese: '葡萄', emoji: '🍇', category: 'fruits' },
  { english: 'strawberry', chinese: '草莓', emoji: '🍓', category: 'fruits' },
  { english: 'watermelon', chinese: '西瓜', emoji: '🍉', category: 'fruits' },
  { english: 'pineapple', chinese: '菠萝', emoji: '🍍', category: 'fruits' },
  { english: 'peach', chinese: '桃子', emoji: '🍑', category: 'fruits' },
  { english: 'mango', chinese: '芒果', emoji: '🥭', category: 'fruits' },
  { english: 'cherry', chinese: '樱桃', emoji: '🍒', category: 'fruits' },
  { english: 'lemon', chinese: '柠檬', emoji: '🍋', category: 'fruits' },
  { english: 'pear', chinese: '梨', emoji: '🍐', category: 'fruits' },
  { english: 'plum', chinese: '李子', emoji: '🫐', category: 'fruits' },
  { english: 'blueberry', chinese: '蓝莓', emoji: '🫐', category: 'fruits' },
  { english: 'kiwi', chinese: '猕猴桃', emoji: '🥝', category: 'fruits' },
  { english: 'coconut', chinese: '椰子', emoji: '🥥', category: 'fruits' },
  { english: 'peanut', chinese: '花生', emoji: '🥜', category: 'fruits' },
  { english: 'melon', chinese: '哈密瓜', emoji: '🍈', category: 'fruits' },
  { english: 'avocado', chinese: '牛油果', emoji: '🥑', category: 'fruits' },
  { english: 'tomato', chinese: '番茄', emoji: '🍅', category: 'fruits' },

  { english: 'red', chinese: '红色', emoji: '🔴', category: 'colors' },
  { english: 'blue', chinese: '蓝色', emoji: '🔵', category: 'colors' },
  { english: 'green', chinese: '绿色', emoji: '🟢', category: 'colors' },
  { english: 'yellow', chinese: '黄色', emoji: '🟡', category: 'colors' },
  { english: 'purple', chinese: '紫色', emoji: '🟣', category: 'colors' },
  { english: 'orange', chinese: '橙色', emoji: '🟠', category: 'colors' },
  { english: 'pink', chinese: '粉色', emoji: '💗', category: 'colors' },
  { english: 'brown', chinese: '棕色', emoji: '🟤', category: 'colors' },
  { english: 'black', chinese: '黑色', emoji: '⚫', category: 'colors' },
  { english: 'white', chinese: '白色', emoji: '⚪', category: 'colors' },
  { english: 'gray', chinese: '灰色', emoji: '🩶', category: 'colors' },
  { english: 'gold', chinese: '金色', emoji: '🪙', category: 'colors' },
  { english: 'silver', chinese: '银色', emoji: '🥈', category: 'colors' },
  { english: 'cyan', chinese: '青色', emoji: '🔵', category: 'colors' },
  { english: 'navy', chinese: '深蓝', emoji: '🔵', category: 'colors' },
  { english: 'coral', chinese: '珊瑚色', emoji: '🩷', category: 'colors' },
  { english: 'lavender', chinese: '薰衣草色', emoji: '💜', category: 'colors' },
  { english: 'mint', chinese: '薄荷绿', emoji: '🌿', category: 'colors' },
  { english: 'peach', chinese: '桃色', emoji: '🍑', category: 'colors' },
  { english: 'sky blue', chinese: '天蓝色', emoji: '☁️', category: 'colors' },

  { english: 'one', chinese: '一', emoji: '1️⃣', category: 'numbers' },
  { english: 'two', chinese: '二', emoji: '2️⃣', category: 'numbers' },
  { english: 'three', chinese: '三', emoji: '3️⃣', category: 'numbers' },
  { english: 'four', chinese: '四', emoji: '4️⃣', category: 'numbers' },
  { english: 'five', chinese: '五', emoji: '5️⃣', category: 'numbers' },
  { english: 'six', chinese: '六', emoji: '6️⃣', category: 'numbers' },
  { english: 'seven', chinese: '七', emoji: '7️⃣', category: 'numbers' },
  { english: 'eight', chinese: '八', emoji: '8️⃣', category: 'numbers' },
  { english: 'nine', chinese: '九', emoji: '9️⃣', category: 'numbers' },
  { english: 'ten', chinese: '十', emoji: '🔟', category: 'numbers' },
  { english: 'eleven', chinese: '十一', emoji: '1️⃣1️⃣', category: 'numbers' },
  { english: 'twelve', chinese: '十二', emoji: '1️⃣2️⃣', category: 'numbers' },
  { english: 'thirteen', chinese: '十三', emoji: '1️⃣3️⃣', category: 'numbers' },
  { english: 'fourteen', chinese: '十四', emoji: '1️⃣4️⃣', category: 'numbers' },
  { english: 'fifteen', chinese: '十五', emoji: '1️⃣5️⃣', category: 'numbers' },
  { english: 'sixteen', chinese: '十六', emoji: '1️⃣6️⃣', category: 'numbers' },
  { english: 'seventeen', chinese: '十七', emoji: '1️⃣7️⃣', category: 'numbers' },
  { english: 'eighteen', chinese: '十八', emoji: '1️⃣8️⃣', category: 'numbers' },
  { english: 'nineteen', chinese: '十九', emoji: '1️⃣9️⃣', category: 'numbers' },
  { english: 'twenty', chinese: '二十', emoji: '2️⃣0️⃣', category: 'numbers' }
]

module.exports = WORD_CATALOG
